### ISSUE TITLE
FireBird driver

### ISSUE THREAD

**Issue by bubnenkoff** [anton-dutov/db#5]
It would be nice to get any driver for FireBird. I understand that SQLLite is much better, but on my job we still using a Firebird databases.

**Comment by anton-dutov** [comment]
Hello,
I don't have any expirience with IBase API, I tried wrote simple Ibase driver, but have some troubles. (Code from qt implementation https://github.com/qtproject/qtbase/blob/dev/src/sql/drivers/ibase/qsql_ibase.cpp).
If you are really interested in. We needs to cooperate (anton.dutov [at] gmail.com)

**Comment by anton-dutov** [comment]
Rare
